name: Publish to npm

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to publish (e.g. 1.0.0)
        required: true
  workflow_call:
    inputs:
      version:
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    environment:
      name: npm
      url: https://www.npmjs.com/package/tree-sitter-glsl-spec
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run: npm version --no-git-tag-version "${{inputs.version}}"
      - run: npm install
      - run: npm publish --provenance --access public
